### ISSUE TITLE
Animated Items not restarting

### ISSUE THREAD

**Issue by Tanguygab** [TrMenu/TrMenu#126]
Hey, I've got an item
```yml
  '#':
    update: 2
    display:
      mat: COAL_ORE
      slots:
        - [0]
        - [9,1]
        - [2,10,18]
        - [3,11,19,27]
        - [4,12,20,28,36]
        - [5,13,21,29,37,45]
        - [6,14,22,30,38,46]
        - [7,15,23,31,39,47]
        - [8,16,24,32,40,48]
        - [17,25,33,41,49]
        - [26,34,42,50]
        - [35,43,51]
        - [44,52]
        - [53]
```
and he has dynamic slots.
My problem is that if I close the menu, and reopen it, the item will be at the same place and continue its way. What I wanted is that the item should start over again

Also, a little suggestion alongside that, could you add a way to make the item stop animating at some point ? like, adding `- stop` at the end of the slots section
```yml
  '#':
    update: 2
    display:
      mat: COAL_ORE
      slots:
        - [0]
        - [9,1]
        - [2,10,18]
        - [3,11,19,27]
        - [4,12,20,28,36]
        - [5,13,21,29,37,45]
        - [6,14,22,30,38,46]
        - [7,15,23,31,39,47]
        - [8,16,24,32,40,48]
        - [17,25,33,41,49]
        - [26,34,42,50]
        - [35,43,51]
        - [44,52]
        - [53]
        - stop
```
Like that, it would be useful =)  thanks !
