### ISSUE TITLE
[Proposal] Additional opportunities

### ISSUE THREAD

**Issue by Shaarper** [TrMenu/TrMenu#138]
Greetings. 
Again, I want to make an offer on the uniqueness of your menu.
And to find out if it's possible to do it at all.

* Adding support to open a menu for a players
> Support to open a menu for a specific player, either a group of people or persons who have a specific permission.
> The team will look like:
> `/trmenu open <menu> -open: <player>`
> `/trmenu open <menu> -openGroup: <player> <player> <player>`
> `/trmenu open <menu> -openPerm: <permission>`
> 
> Just so the player can't close this menu by accident. Or he couldn't close it at all. Or he could close it only the administrator, or by pressing the button in the menu.
> Close command:
> `/trmenu close <menu> -close: <player>`
> `/trmenu close <menu> -closeGroup: <player> <player> <player>`
> `/trmenu close <menu> -closePerm: <permission>`

Also, I still want to see menu support for several languages.
Let me try to explain how I see it.

* Multi-language support on the menu
> Add the ability to change the language just for yourself.
> What does that mean? I open the lang menu. There I choose a specific language that I like.
> A team to change the language: 
> `/trmenu lang English`
> 
> Now let's see how roughly I can imagine what the Multi-Menu would look like.
> We have what's known as the **settings.yml** setting.
> It adds a Lang entry.
```yaml
Multi-Language:
 # Enabling and disabling this function
 lang-enabled: true

  # Download folder for all menus
 Load-Menu:
   - 'English'

 # Here you type which folders will be created in the folder that is written above.
 Menu-Locale:
   - 'en_US'
   - 'zh_CN'
```
> Now let's move on to the menu itself. 
> For example, we have an **English** folder and there is our menu.
> A value will be added to the menu itself
```yaml
Options:
  Locale: English
```
> Which would mean that this menu uses the **English** configuration.
> And a person with a configuration like **zh_CN** cannot open this menu. He will open the same menu, but with the **zh_CN** configuration.
>Also if I add another language to **settings.yml**, like **ru_RU**. Automatically create folder **ru_RU** and all menus will be identically copied to the new folder.
