### ISSUE TITLE
Error when loading player's head with '<head:%player_name%>'

### ISSUE THREAD

**Issue by SrBedrock** [TrMenu/TrMenu#147]
## Menu:

```yml
Title: '&6» Sistema de Lojas!'

Shape:
  - 'BBBBBBBBB'
  - 'B+B|AB=#B'
  - 'BBBBBBBBB'
  - 'BBBB-BBBB'

Buttons:
  '#':
    display:
      material: '<skull:eyJ0ZXh0dXJlcyI6eyJTS0lOIjp7InVybCI6Imh0dHA6Ly90ZXh0dXJlcy5taW5lY3JhZnQubmV0L3RleHR1cmUvZDAxYWZlOTczYzU0ODJmZGM3MWU2YWExMDY5ODgzM2M3OWM0MzdmMjEzMDhlYTlhMWEwOTU3NDZlYzI3NGEwZiJ9fX0=>'
      name: '&a» Sobre a Loja de Jogadores!'
      lore:
      - ''
      - '&a• &fPara criar uma loja, com o'
      - '&f  item que deseja vender na mão'
      - '&f  segure shift e clique com o'
      - '&f  botão esquerdo no baú.'
      - ''
      - '&a• &ePara criar uma warp use:'
      - '&a• &c/go definir [nome]'
      - ''
      - '&a• &fEx: &c/go definir Loja'
      - ''
      - '&a• &ePara definir uma categoria:'
      - '&a• &c/go categ [warp] [categoria]'
      - ''
      - '&aPara listar lojas use &c/go'
    actions:
      all:
      - 'player: pwarp'

  '-':
    display:
      material: NETHER_STAR
      name: '&eMenu Principal'
      lore: []
    actions:
      all:
      - 'open: menu'

  +:
    display:
      material: '<head:%player_name%>'
      name: '&2• %vault_rank% %essentials_nickname%'
      lore:
      - '&e• &fSaldo: &2$ &a%vault_eco_balance_formatted%'

  '|':
    display:
      material: '<skull:eyJ0ZXh0dXJlcyI6eyJTS0lOIjp7InVybCI6Imh0dHA6Ly90ZXh0dXJlcy5taW5lY3JhZnQubmV0L3RleHR1cmUvNDNjYjI3OWZkMDYxZjQ2MjFlZTc1NGE0YWU3ZWEyZDllODFlOTVjYWU1Yzk1OWYzOWY0MmIzM2U5YWIzMTEifX19>'
      name: '&e♕ &6Loja do Servidor &e♕'
      lore:
      - ''
      - '&a• Clique aqui para abrir a'
      - '&a  loja do server.'
      - ''
      - '&f• Acesse a loja direto com'
      - '&c  /sloja &fou &c/sshop'
    actions:
      all:
      - 'player: sshop'
      - 'refresh'

  =:
    display:
      material: '<skull:eyJ0ZXh0dXJlcyI6eyJTS0lOIjp7InVybCI6Imh0dHA6Ly90ZXh0dXJlcy5taW5lY3JhZnQubmV0L3RleHR1cmUvMzA5OGQ0ZWY0OGVlOWI5Y2NmMTM3MmEwYzVmYjlkYmU3MzUyZTFmYTJiNDg0OWJjM2RjNTQyMzdmNGU3YzU4OSJ9fX0=>'
      name: '&e★ &6Loja de Jogadores &e★'
      lore:
      - ''
      - '&a• Clique aqui para listar'
      - '&a  as lojas de jogadores.'
      - ''
      - '&f• Liste lojas direto com'
      - '&c  /pwarp &fou &c/go'
    actions:
      all:
      - 'player: pwarp'

  A:
    display:
      material: '<skull:eyJ0ZXh0dXJlcyI6eyJTS0lOIjp7InVybCI6Imh0dHA6Ly90ZXh0dXJlcy5taW5lY3JhZnQubmV0L3RleHR1cmUvZDAxYWZlOTczYzU0ODJmZGM3MWU2YWExMDY5ODgzM2M3OWM0MzdmMjEzMDhlYTlhMWEwOTU3NDZlYzI3NGEwZiJ9fX0=>'
      name: '&a» Sobre a Loja do Server!'
      lore:
      - ''
      - '&a• &fPara vender para a loja do server'
      - ' &f  Use o comando &c/sell hand &e[quantia]'
      - ' &f  com o item na mão para vende-lô.'
      - ''
      - '&a• &fUse o comando &c/sell handall'
      - '&f  para vender todos os itens no'
      - '&f  inventário que são do mesmo'
      - '&f  tipo do item que está na mão.'
      - ''
      - '&a• &fUse o comando &c/sell all'
      - '&f  para vender todos os itens'
      - '&f  que estão no seu inventário.'
      - ''
      - '&aPara abrir a loja do server use &c/sloja'
    actions:
      all:
      - 'player: sshop'
      - 'refresh'
  B:
    display:
      material: GRAY_STAINED_GLASS_PANE
      name: '&f '
      lore: []
```

## settings.yml

```yml
# 
# Configuration
Options:
  Debug: false
  Locale: en_US
  Hide-Logo: true
  Skull-Mojang-API: false
Load-Menu-Files:
- plugins/CustomMenusFolder
Actions:
  Catcher-Cancel-Words:
  - (?i)cancel|cancel!|quit|exit|end|stop|
Item:
  Default-Color-Name: '&7'
  Default-Color-Lore: '&7'
Shortcuts:
  Offhand: []
  Sneaking-Offhand: []
  Right-Click-Player: []
  Sneaking-Right-Click-Player: []
  PlayerInventory-Border-Left: []
  PlayerInventory-Border-Right: []
  PlayerInventory-Border-Middle: []
RegisterCommands:
  # ------------------------- #
  #  UPDATE 2020/08/17 17:37  #
  # ------------------------- #
  # openMenus:
    # aliases: []
#     # execute: ['tell: &7Argument `example` Required!']
#     # arguments: {example: 'open: example'}

  menu:
    aliases: []
    execute:
    - 'open: menu'
    arguments: []
  ticket:
    aliases:
    - tickets
    execute:
    - 'open: ticket'
    arguments: []
  kits:
    aliases: []
    execute:
    - 'open: kits'
    arguments: []
  stats:
    aliases: []
    execute:
    - 'open: stats'
    arguments: []
  prot:
    aliases:
    - plot
    - protecao
    - proteger
    execute:
    - 'open: protecao'
    arguments:
      criar: 'open: protecao-criar'
      config: 'open: protecao-loja'
      loja: 'open: protecao-loja'
      permissao: 'open: protecao-perm'
  baltop:
    aliases:
    - topsaldo
    - topmoney
    - baltop
    - balancetop
    execute:
    - 'open: baltop'
    arguments: []
  loja:
    aliases:
    - shop
    execute:
    - 'open: loja'
    arguments: []
  vipmenu:
    aliases:
    - viptime
    - vipstatus
    permission: armamc.vip
    execute:
    - 'open: vipmenu'
    arguments: []
Events-Ignore-Cancelled:
  PlayerCommandPreprocessEvent: true
  InventoryOpenEvent: true
  InventoryClickEvent: true

# --------------------------------------------- #
# HASH 992ede2fca75429152af82783890f5192fb17548 #
# --------------------------------------------- #

```

## Error on console:

```
[17:48:42 WARN]: java.io.FileNotFoundException: https://api.ashcon.app/mojang/v2/user/Alana02
[17:48:42 WARN]: at java.base/sun.net.www.protocol.http.HttpURLConnection.getInputStream0(HttpURLConnection.java:1923)
[17:48:42 WARN]: at java.base/sun.net.www.protocol.http.HttpURLConnection.getInputStream(HttpURLConnection.java:1523)
[17:48:42 WARN]: at java.base/sun.net.www.protocol.https.HttpsURLConnectionImpl.getInputStream(HttpsURLConnectionImpl.java:224)
[17:48:42 WARN]: at java.base/java.net.URL.openStream(URL.java:1167)
[17:48:42 WARN]: at me.arasple.mc.trmenu.boot.internal.IO.readFromURL(IO.java:36)
[17:48:42 WARN]: at me.arasple.mc.trmenu.utils.Skulls$getPlayerTexture$1.run(Skulls.kt:80)
[17:48:42 WARN]: at org.bukkit.craftbukkit.v1_16_R1.scheduler.CraftTask.run(CraftTask.java:99)
[17:48:42 WARN]: at org.bukkit.craftbukkit.v1_16_R1.scheduler.CraftAsyncTask.run(CraftAsyncTask.java:58)
[17:48:42 WARN]: at com.destroystokyo.paper.ServerSchedulerReportingWrapper.run(ServerSchedulerReportingWrapper.java:22)
[17:48:42 WARN]: at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1130)
[17:48:42 WARN]: at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:630)
[17:48:42 WARN]: at java.base/java.lang.Thread.run(Thread.java:832)
[17:48:42 INFO]: [TrMenu] ERROR | An exception occurred when obtaining the player's head texture asynchronously, check the following errors!
[17:48:42 INFO]: Reason: null
[17:48:42 INFO]: Trace: [me.arasple.mc.trmenu.utils.Skulls$getPlayerTexture$1.run(Skulls.kt:80)
]
```
