### ISSUE TITLE
图标优先级判定的问题

### ISSUE THREAD

**Issue by Score2** [TrMenu/TrMenu#172]
**Describe the bug**
图标优先级判定的问题

**Server Software**
git-Paper-0893de14 (MC: 1.16.2) (Implementing API 版本 1.16.2-R0.1-SNAPSHOT)

**Plugins**
 - TrMenu 2.04-DEV
 - PlaceholderAPI 2.10.9

**To Reproduce**
已在下方用符号 `#` 注明
```
title: '&8物品维修'

layout:
- '=-------='
- '-   r   -'
- '=-------='

events:
  # 这部分正常判定
  open:
  - 'tell: &a%vault_eco_balance_fixed% >= &c${cost}'
  - 'tell: &etrue <require:%vault_eco_balance_fixed% >= ${cost}>'
  close:
  - 'reset'

buttons:
  '=':
    display:
      mats: 'BLACK_STAINED_GLASS_PANE'
      name: ' '
  '-':
    display:
      mats: 'GRAY_STAINED_GLASS_PANE'
      name: ' '


  'r':
    refresh: [-1, -1, 10, -1]
    display:
      mats: 'ARMOR_STAND'
      name: '&b物品维修'
      lore:
      - ''
      - '&7根据你主手中的工具或武器'
      - '&7的附魔数或价值计算所需花费'
      - ''
      - '&7耐久比: &b%javascript_island_group_item_mainhand_durability%%'
      - '&7魔咒价值: &5&l%javascript_island_group_item_mainhand_enchant_values%'
      - ''
      - '&7你的银币: &6%vault_eco_balance_fixed%'
      - '&7维修当前手中物品所需 &6${cost} &7银币'
      - ''
      - '&c银币不足, 缺少 &6%math_${cost} - {vault_eco_balance_fixed}[precision:0]% &c个银币!'
    icons:
    - condition: '"%javascript_island_group_item_mainhand_type%" == "UNKNOWN"'
      display:
        name: '&b物品维修'
        mats: 'BARRIER'
        lore:
        - ''
        - '&7根据你主手中的工具或武器'
        - '&7的附魔数或价值计算所需花费'
        - ''
        - '&7你的银币: &6%vault_eco_balance_fixed%'
        - ''
        - '&c请使用工具或武器右键铁砧!'
    - condition: '"%javascript_island_group_item_mainhand_durability%" == "100"'
      display:
        mats: 'STRUCTURE_VOID'
        name: '&b物品维修'
        lore:
        - ''
        - '&7根据你主手中的工具或武器'
        - '&7的附魔数或价值计算所需花费'
        - ''
        - '&7耐久比: &b%javascript_island_group_item_mainhand_durability%%'
        - '&7魔咒价值: &5&l%javascript_island_group_item_mainhand_enchant_values%'
        - ''
        - '&7你的银币: &6%vault_eco_balance_fixed%'
        - ''
        - '&3该物品耐久已满, 无需修复!'
    # 在这里的表达式不会正确判定
    - condition: '%vault_eco_balance_fixed% >= ${cost}'
      display:
        mats: '<hdb:4010>'
        name: '&b物品维修'
        lore:
        - ''
        - '&7根据你主手中的工具或武器'
        - '&7的附魔数或价值计算所需花费'
        - ''
        - '&7耐久比: &b%javascript_island_group_item_mainhand_durability%%'
        - '&7魔咒价值: &5&l%javascript_island_group_item_mainhand_enchant_values%'
        - ''
        - '&7你的银币: &6%vault_eco_balance_fixed%'
        - '&7维修当前手中物品所需 &6${cost} &7银币'
        - ''
        - '&c&l敬请期待'

Functions:
  cost: |-
    function cost() {
        #  隐私原因，公式不公开，如有需要，私信获取。
    }
    cost()
```

**Expected behavior**
上方配置文件中的表达式 `%vault_eco_balance_fixed% >= ${cost}` 在优先级图标部分不会被正确解析
在其它地方（event.open 处）正常解析。

**Screenshots**
![1](https://i.loli.net/2020/08/28/TNVkMhpj6uRtmid.png)
从图中不难看出，经过变量 `%math_${cost} - {vault_eco_balance_fixed}[precision:0]%` 的解析得到的数字为负，按常理来看这不可能会发生，因为有优先级表达式 `%vault_eco_balance_fixed% >= ${cost}`，本应该显示这个图标：
```
      display:
        mats: '<hdb:4010>'
        name: '&b物品维修'
        lore:
        - ''
        - '&7根据你主手中的工具或武器'
        - '&7的附魔数或价值计算所需花费'
        - ''
        - '&7耐久比: &b%javascript_island_group_item_mainhand_durability%%'
        - '&7魔咒价值: &5&l%javascript_island_group_item_mainhand_enchant_values%'
        - ''
        - '&7你的银币: &6%vault_eco_balance_fixed%'
        - '&7维修当前手中物品所需 &6${cost} &7银币'
        - ''
        - '&c&l敬请期待'
```
而不是这个图标：
```
    display:
      mats: 'ARMOR_STAND'
      name: '&b物品维修'
      lore:
      - ''
      - '&7根据你主手中的工具或武器'
      - '&7的附魔数或价值计算所需花费'
      - ''
      - '&7耐久比: &b%javascript_island_group_item_mainhand_durability%%'
      - '&7魔咒价值: &5&l%javascript_island_group_item_mainhand_enchant_values%'
      - ''
      - '&7你的银币: &6%vault_eco_balance_fixed%'
      - '&7维修当前手中物品所需 &6${cost} &7银币'
      - ''
      - '&c银币不足, 缺少 &6%math_${cost} - {vault_eco_balance_fixed}[precision:0]% &c个银币!'
```
通过变量解析发现，%vault_eco_balance_fixed%是一定大于等于${cost}的，但优先级表达式这里却为false。

**Environment(please complete the following information):**
 - OS: [e.g. Windows Server 2019]
 - JDK: [e.g.1.8.0_222]

**Additional context**
无
