### ISSUE TITLE
Logs feature

### ISSUE THREAD

**Issue by Tanguygab** [TrMenu/TrMenu#188]
**Type**
Updated Functionnality

**Description**
TrMenu already has logs, but they don't seem to log much things, (I've only found shape changing so far), so I'm suggesting a way to log more things !

**Usage**
A global settings for all menus in the `settings.yml` file

For the logged events, actions and expressions, you can use * to specify all of them, and put a - before to not specify them (useful if you use * and - at the same time)  

It could also support a per menu log file

**Example**
Settings.yml
```yml
logs:
  enabled: true
  file: '/plugins/TrMenu/logs/'
  # logged events
  events:
    - *
    - -click
  # logged actions
  actions:
    - *
    - -tell
  # logged checked expressions (when you click a button which has conditions)
  expressions:
    - *
   - -isOp
```

Per Menu file
```yml
logs:
  # Set to true by default when not specified
  enabled: true
  # If not specified, will use the global file in the settings.yml file
  file: '/plugins/TrMenu/logs/ExampleMenu/'
 ```
