### ISSUE TITLE
添加用于获取菜单中节点的变量

### ISSUE THREAD

**Issue by Score2** [TrMenu/TrMenu#208]
**Type**
在任意图标中：
```
  efficiency:
    custom:
      name: efficiency
      type: '附魔'
      cost: 100
    display:
      mats: '<hdb:19458>'
      name: '&b该图标的名称是: &f${node:icons.<self>.custom.name}，但不能读取本身: ${node:icons.<self>.display.name}(这段变量不会被解析)'
      lore:
      - '&f该图标的材质是: ${node:icons.<self>.display.material}'
      - '&f这个物品属于: ${node:icons.<self>.custom.type}, 附魔一次需要花费: ${node:icons.<self>.custom.cost}'
      - '&f如果某个节点为list, 那么不会被解析，比如lore，${node.icons.<self>.display.lore}'
```
解析后的结果应该为：
```
  efficiency:
    custom:
      name: efficiency
      type: '附魔'
      cost: 100
    display:
      mats: '<hdb:19458>'
      name: '&b该图标的名称是: &f**efficiency**，但不能读取本身: **${node:icons.<self>.display.name}**(这段变量不会被解析)'
      lore:
      - '&f该图标的材质是: **<hdb:19458>**'
      - '&f这个物品属于: **附魔**, 附魔一次需要花费: **100**'
      - '&f如果某个节点为list, 那么不会被解析，比如lore，**${node.icons.<self>.display.lore}**'
```
**加粗**部分为猜想的解析结果

**Description**
更好的促进菜单图标模块化管理，减轻编写大量图标重复内容的负担。
比如修改价格，通常使用替换可能与其它相同节点的value冲突

**Usage**
`上方已展示出配置文件`

**Example**
`上方已展示出配置文件`

**Additional context**
None
