### ISSUE TITLE
RegisterCommands player tab-completition

### ISSUE THREAD

**Issue by Okan-SEREN** [TrMenu/TrMenu#209]
- [ ] Player tab-complete feature to RegisterCommands section

**Example**

  Profile:
    aliases: []
    execute:
    - 'tell: &7enter a "player name".'
    arguments:
      playernames: 'open: profile'

  Profile:
    aliases: []
    execute:
    - 'tell: &7enter a "player name".'
    arguments:
      {playername}: 'open: profile {playername}'

**Comment by Arasple** [comment]
```YAML
  profile:
    execute:
      - condition: 'isOnline.{0}'
        list: 'player: profile {0}'
        deny: 'tell: Please enter a player''s name'
```
