### ISSUE TITLE
Built-in scripts not parsed in Event section

### ISSUE THREAD

**Issue by BBSnowIce** [TrMenu/TrMenu#265]
**Describe the bug**
Built-in scripts seems to be not parsed in the Event section.

**To Reproduce**
Simply try to set a built-in script in open condition or text and you'll see it's not parsed.

**Expected behavior**
The script parsed.

Using last version available on spigot.

**Comment by Flaimer2** [comment]
Use a placeholder: %trmenu_js_<Expression>%

**Comment by BBSnowIce** [comment]
Placeholders seems to be not parsed too...

**Comment by Tanguygab** [comment]
send your menu file and show where the script is not parsed

**Comment by BBSnowIce** [comment]
This is not exactly the same problem but still, this is a problem in condition section, placeholders seem to be not parsed, I can't buy anything on this shop menu
```yml
Title:
  - '&3&lSHOP'

Layout:
- - '||||$||||'
  - '| `remove1`   `add1` |'
  - '| `remove8` ^ `add8` |'
  - '| `remove16`   `add16` |'
  - '||²|`BACK`|²||'
- - 'A   B   C'
  - 'DEFGHIJKL'
  - '    M    '
- - ' `AAA``AAB``AAC``AAD``AAE``AAF``AAG` '
  - ' `AAH``AAI``AAJ``AAK``AAL``AAM``AAN` '
  - '  `AAO``AAP` `AAQ``AAR`  '
  - '    `BACK`    '
  
Options:
  Arguments: true
  Default-Arguments: []
  Default-Layout: 1
  Hide-Player-Inventory: false
  Min-Click-Delay: 200

Bindings:
  Commands:
    - '(?i)testshop'
#
# {0} Item Display Name
# {1} Item Material
# {2} Buy Price
# {3} Item
# {4} Amount
#

Buttons:
  'AAA':
    update: -1
    display:
      material: STONE
    actions:
      all:
        - 'set-args: `pierre` STONE 10 STONE `1`'
        - 'set-shape: 0'
  'A':
    update: -1
    display:
      material: STONE
    actions:
      all:
        - 'set-shape: 2'
  'BACK':
    update: -1
    display:
      material: 'SPRUCE_DOOR'
      name: '&4&lBack'
    actions:
      all:
        - 'set-shape: 1'
  '^':
    update: 1
    display:
      material: '{1}'
      name: '&3{4}x &e{0}'
      amount: '{4}'
      lore:
        - '"%vault_eco_balance%" >= "%math_{2}*{4}%"'
    actions:
      left:
        - condition: '"%vault_eco_balance%" >= "%math_{2}*{4}%"'
          pri: 2
          actions:
            - 'give-item: material:{3},amount:{4}'
            - 'take-money: %math_{4}*{2}[precision:0]%'
            - 'tell: success'
            - 'refresh'
            - 'return'
        - condition: 'true'
          pri: 1
          actions:
              - 'tell: not enough'
  'add1':
    display:
      name: '+1'
      material: '<skull: eyJ0ZXh0dXJlcyI6eyJTS0lOIjp7InVybCI6Imh0dHA6Ly90ZXh0dXJlcy5taW5lY3JhZnQubmV0L3RleHR1cmUvNWZmMzE0MzFkNjQ1ODdmZjZlZjk4YzA2NzU4MTA2ODFmOGMxM2JmOTZmNTFkOWNiMDdlZDc4NTJiMmZmZDEifX19>'
      amount: 1
    actions:
      all:
        - 'set-args: {0} `{1}` {2} {3} %math_{4}+1[precision:0]%'
        - 'refresh'
    icons:
      - condition: '{4} >= 64'
        display:
          material: 'RED_STAINED_GLASS_PANE'
          name: ' '
  'add8':
    display:
      name: '+8'
      material: '<skull: eyJ0ZXh0dXJlcyI6eyJTS0lOIjp7InVybCI6Imh0dHA6Ly90ZXh0dXJlcy5taW5lY3JhZnQubmV0L3RleHR1cmUvNWZmMzE0MzFkNjQ1ODdmZjZlZjk4YzA2NzU4MTA2ODFmOGMxM2JmOTZmNTFkOWNiMDdlZDc4NTJiMmZmZDEifX19>'
      amount: 8
    actions:
      all:
        - 'set-args: {0} `{1}` {2} {3} %math_{4}+8[precision:0]%'
        - 'refresh'
    icons:
      - condition: '{4} >= 57'
        display:
          material: 'RED_STAINED_GLASS_PANE'
          name: ' '
  'add16':
    display:
      name: '+16'
      material: '<skull: eyJ0ZXh0dXJlcyI6eyJTS0lOIjp7InVybCI6Imh0dHA6Ly90ZXh0dXJlcy5taW5lY3JhZnQubmV0L3RleHR1cmUvNWZmMzE0MzFkNjQ1ODdmZjZlZjk4YzA2NzU4MTA2ODFmOGMxM2JmOTZmNTFkOWNiMDdlZDc4NTJiMmZmZDEifX19>'
      amount: 16
    actions:
      all:
        - 'set-args: {0} `{1}` {2} {3} %math_{4}+16[precision:0]%'
        - 'refresh'
    icons:
      - condition: '{4} >= 49'
        display:
          material: 'RED_STAINED_GLASS_PANE'
          name: ' '
  'remove1':
    display:
      name: '-1'
      material: '<skull: eyJ0ZXh0dXJlcyI6eyJTS0lOIjp7InVybCI6Imh0dHA6Ly90ZXh0dXJlcy5taW5lY3JhZnQubmV0L3RleHR1cmUvNGU0YjhiOGQyMzYyYzg2NGUwNjIzMDE0ODdkOTRkMzI3MmE2YjU3MGFmYmY4MGMyYzViMTQ4Yzk1NDU3OWQ0NiJ9fX0=>'
      amount: 1
    actions:
      all:
        - 'set-args: {0} `{1}` {2} {3} %math_{4}-1[precision:0]%'
        - 'refresh'
    icons:
      - condition: '{4} <= 1'
        display:
          material: 'RED_STAINED_GLASS_PANE'
          name: ' '
  'remove8':
    display:
      name: '-8'
      material: '<skull: eyJ0ZXh0dXJlcyI6eyJTS0lOIjp7InVybCI6Imh0dHA6Ly90ZXh0dXJlcy5taW5lY3JhZnQubmV0L3RleHR1cmUvNGU0YjhiOGQyMzYyYzg2NGUwNjIzMDE0ODdkOTRkMzI3MmE2YjU3MGFmYmY4MGMyYzViMTQ4Yzk1NDU3OWQ0NiJ9fX0=>'
      amount: 8
    actions:
      all:
        - 'set-args: {0} `{1}` {2} {3} %math_{4}-8[precision:0]%'
        - 'refresh'
    icons:
      - condition: '{4} <= 8'
        display:
          material: 'RED_STAINED_GLASS_PANE'
          name: ' '
  'remove16':
    display:
      name: '-16'
      material: '<skull: eyJ0ZXh0dXJlcyI6eyJTS0lOIjp7InVybCI6Imh0dHA6Ly90ZXh0dXJlcy5taW5lY3JhZnQubmV0L3RleHR1cmUvNGU0YjhiOGQyMzYyYzg2NGUwNjIzMDE0ODdkOTRkMzI3MmE2YjU3MGFmYmY4MGMyYzViMTQ4Yzk1NDU3OWQ0NiJ9fX0=>'
      amount: 16
    actions:
      all:
        - 'set-args: {0} `{1}` {2} {3} %math_{4}-16[precision:0]%'
        - 'refresh'
    icons:
      - condition: '{4} <= 16'
        display:
          material: 'RED_STAINED_GLASS_PANE'
          name: ' '
```

**Comment by Tanguygab** [comment]
what's your TrMenu version? also do you have PlaceholderAPI?

**Comment by BBSnowIce** [comment]
Last Build available on github (TrMenu: 2.08 / Sat Dec 26 12:44:48 CET 2020 (Built by runner)) and I do have PlaceholderAPI (PlaceholderAPI - 2.10.9)

**Comment by Tanguygab** [comment]
can you try to make a video of the problem?

**Comment by BBSnowIce** [comment]
Sure there it is : https://youtu.be/Ie3G-rcmx5o

**Comment by Tanguygab** [comment]
```yml
        - condition: '"%vault_eco_balance%" >= "%math_{2}*{4}%"'
          pri: 2
          actions:
            - 'give-item: material:{3},amount:{4}'
            - 'take-money: %math_{4}*{2}[precision:0]%'
            - 'tell: success'
            - 'refresh'
            - 'return'
        - condition: 'true'
          pri: 1
          actions:
              - 'tell: not enough'
```
utilise les `deny-actions` à la place
```yml
        - condition: '"%vault_eco_balance%" >= "%math_{2}*{4}%"'
          pri: 2
          actions:
            - 'give-item: material:{3},amount:{4}'
            - 'take-money: %math_{4}*{2}[precision:0]%'
            - 'tell: success'
            - 'refresh'
          deny-actions:
              - 'tell: not enough'
```
